# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sodaseo', '0010_auto_20150925_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='path',
            field=models.CharField(help_text='Formato: /url-da-pagina/', max_length=255, verbose_name='caminho'),
        ),
    ]
